### ISSUE TITLE
Parallel support broke pipeline 

### ISSUE THREAD

**Issue by romulets** [andrcuns/allure-publish-action#40]
[The addition of parallel support](https://github.com/andrcuns/allure-publish-action/commit/f504d906a844a32d2547c7aa35b62a3f8cba667d) broke our pipeline. See below the error

```
/usr/bin/docker run --name b661bdd9122f947f4f058385faa293ef996b_0d9348 --label 24b661 --workdir /github/workspace --rm -e "AWS_REGION" -e "ALLURE_S3_BUCKET" -e "S3_BUCKET_ALLURE_REPORT_AP" -e "GITHUB_AUTH_TOKEN" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "INPUT_STORAGETYPE" -e "INPUT_RESULTSGLOB" -e "INPUT_UPDATEPR" -e "INPUT_COLLAPSESUMMARY" -e "INPUT_SUMMARY" -e "INPUT_SUMMARYTABLETYPE" -e "INPUT_COPYLATEST" -e "INPUT_BUCKET" -e "INPUT_PREFIX" -e "INPUT_IGNOREMISSINGRESULTS" -e "INPUT_DEBUG" -e "INPUT_BASEURL" -e "INPUT_REPORTTITLE" -e "INPUT_FLAKYWARNINGSTATUS" -e "INPUT_COLOR" -e "INPUT_PARALLEL" -e "INPUT_REPORTNAME" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/cloudbeat/cloudbeat":"/github/workspace" 24b661:bdd9122f947f4f058385faa293ef996b  "--results-glob=tests/allure/results" "--bucket=csp-allure-reports" "--prefix=allure_reports/cloudbeat/ci/2284" "--update-pr=actions" "--summary=suites" "--summary-table-type=markdown" "--collapse-summary=false" "--report-title=" "--copy-latest=true" "--ignore-missing-results=true" "--flaky-warning-status=" "--color=true" "--base-url=" "--debug=false" "--parallel=8" "s3"

getopt: unrecognized option: parallel=8
Unexpected option provided: '--base-url:parallel:report-name'
```

([Also available in our public project gh actions](https://github.com/elastic/cloudbeat/actions/runs/9641938350/job/26589657544?pr=2284))

[Our github action configuration](https://github.com/elastic/cloudbeat/blob/main/.github/workflows/ci.yml#L245-L265)
```yaml
    - name: Publish allure report
        if: ${{ always() }}
        uses: andrcuns/allure-publish-action@v2.7.0
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          storageType: s3
          resultsGlob: "tests/allure/results"
          updatePr: actions
          collapseSummary: false
          summary: suites
          summaryTableType: markdown
          copyLatest: true
          bucket: csp-allure-reports
          prefix: allure_reports/cloudbeat/ci/${{ github.event.number }}
          ignoreMissingResults: true
          debug: false
```

I couldn't think of any workaround to make it work, since even if I provide a 1 as `parallel` argument, the parameter is still used. Therefore I'm rolling it back in our project.

Let me know if you need further information to test it!
