### ISSUE TITLE
Configuring report url with bucket and prefix

### ISSUE THREAD

**Issue by micahjsmith** [andrcuns/allure-publish-action#50]
I'm having an issue configuring the report url. I'm serving the bucket as a static site. Thus `https://mydomain/` serves `gs://mybucket/index.html`. With my configuration below, allure-publish-action generates report urls of the form `https://mydomain/mybucket/$prefix/index.html`. This is incorrect, as `mybucket` should not be part of the path since it is served at the root domain. When I remove `mybucket` from the URL, the resulting URL does work. Is it possible to configure this within the action? I know that I can update my static site hosting to serve the bucket at the `mybucket` prefix but seems like this shouldn't be necessary. Thanks!

```
      - name: Publish allure report
        uses: andrcuns/allure-publish-action@v2.9.0
        env:
          <elided>
        with:
          storageType: gcs
          resultsGlob: .allure
          bucket: mybucket
          prefix: $GITHUB_REF
          copyLatest: false
          updatePr: actions
          ignoreMissingResults: true
          baseUrl: https://mydomain
```

Curently urls look like this
```
Report url: https://mydomain/mybucket/refs/pull/<pull>/merge/<merge>/index.html
Latest report url: https://mydomain/mybucket/refs/pull/<pull>/merge/index.html
```
